# Generated by Django 2.0.6 on 2018-06-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_use', models.CharField(max_length=100)),
                ('category_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='dresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_title', models.CharField(max_length=100)),
                ('dress_price', models.IntegerField()),
                ('dress_logo', models.CharField(max_length=1000)),
                ('dress_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Category')),
            ],
        ),
    ]
