# Generated by Django 2.0.6 on 2018-06-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
